# Generated by Django 2.2.5 on 2019-10-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Furniture', 'Furniture'), ('Personal', 'Personal'), ('Food & Drink', 'Food & Drink')], max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc_short', models.CharField(max_length=200)),
                ('desc_long', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
