# Generated by Django 2.2.5 on 2019-09-29 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Product', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Furniture', 'Furniture'), ('Personal', 'Personal'), ('Food & Drink', 'Food & Drink')], max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc_short', models.CharField(max_length=200)),
                ('desc_long', models.CharField(max_length=1000)),
            ],
        ),
    ]
