# Generated by Django 2.2.5 on 2019-10-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Management', 'Management'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Information Technology', 'Information Technology'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Legal', 'Legal'), ('Human Resources', 'Human Resources')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
