# Generated by Django 2.2.5 on 2019-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=123, upload_to='images'),
            preserve_default=False,
        ),
    ]
