# Generated by Django 2.2.5 on 2019-10-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Information Technology', 'Information Technology'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Legal', 'Legal'), ('Human Resources', 'Human Resources')], max_length=30),
        ),
    ]
